
services:
  db:
    image: postgres:15
    container_name: express_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro 
volumes:
  db_data: